#! /bin/sh 
#
# This is an init script for openembedded
# Copy it to /etc/init.d/thttpd and type
# > update-rc.d thttpd defaults 60
#


thttpd=/usr/sbin/thttpd
test -x "$thttpd" || exit 0


case "$1" in
  start)
    echo -n "Starting thttpd"
    start-stop-daemon --start --quiet --exec $thttpd -- -d /srv/www -u root -c "/cgi-bin/*"
    echo "."
    ;;
  stop)
    echo -n "Stopping thttpd"
    start-stop-daemon --stop --quiet --exec $thttpd -u root
    echo "."
    ;;
  reload|force-reload)
    start-stop-daemon --stop --quiet --signal 1 --exec $thttpd -u root
    ;;
  restart)
    echo -n "Stopping thttpd"
    start-stop-daemon --stop --quiet --exec $thttpd -- -u root
    echo "."
    echo -n "Waiting for thttpd to die off"
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo ""
    echo -n "Starting thttpd"
    start-stop-daemon --start --quiet --exec $thttpd -- -d /srv/www -u root -c "/cgi-bin/*"
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/thttpd {start|stop|reload|restart|force-reload}"
    exit 1
esac

exit 0
